### ISSUE TITLE
todo: FontInfoLabel

### ISSUE THREAD

**Issue by letelete** [letelete/Fontly#2]
- [x] **IMPORTANT** Add to the fontInfoLabel: info about size and type of the font 
- [ ]  **IMPORTANT** Add to the fontInfoLabel:  "ADD TO FOLDER" button, "ADD TO FAVOURITES" button.
- [ ] **IMPORTANT** Style the onhover, active etc. + add padding + add left-border-radius to font info
