### ISSUE TITLE
todo: UI

### ISSUE THREAD

**Issue by letelete** [letelete/Fontly#4]
- [x] **IMPORTANT** Fix padding in QListView when setting a background color
- [x] **IMPORTANT** Apply new design to app
- [x] **IMPORTANT** Add on hover/pressed etc. to every button

- [x] Style the horizontal & vertical scrollbar.
